application:
  actions: actions
  runtimeManifest:
    packages:
      24petwatch-appbuilder:
        license: Apache-2.0
        actions:
          authentication-salesforce:
            function: actions/salesforce-abandoned-cart/authentication.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              SALESFORCE_CLIENT_ID: $SALESFORCE_CLIENT_ID
              SALESFORCE_CLIENT_SECRET: $SALESFORCE_CLIENT_SECRET
              SALESFORCE_AUTH_URI: $SALESFORCE_AUTH_URI
              SALESFORCE_ACCOUNT_ID: $SALESFORCE_ACCOUNT_ID
              SALESFORCE_SCOPES: "data_extensions_write data_extensions_read journeys_read list_and_subscribers_read"
          salesfore-event:
            function: actions/salesforce-abandoned-cart/salesforce.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              SALESFORCE_REST_EVENTS_URI: $SALESFORCE_REST_EVENTS_URI
              SALESFORCE_REST_EVENTS_UPSERT_URI: $SALESFORCE_REST_EVENTS_UPSERT_URI
              SALESFORCE_EVENT_DEFINITION: "APIEvent-6723a35b-b066-640c-1d7b-222f98caa9e1"
          contact-form:
            function: actions/contact-form/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotions:
              require-adobe-auth: false
              final: true
          service-pethealth:
            function: actions/cart-service/pethealth.js
            web: 'false'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              PETHEALTH_BASE_DOMAIN: $PETHEALTH_BASE_DOMAIN
          authentication-pethealth:
            function: actions/cart-service/authentication.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              PETHEALTH_USERNAME: $PETHEALTH_USERNAME
              PETHEALTH_API_KEY: $PETHEALTH_API_KEY
              PETHEALTH_BASE_DOMAIN: $PETHEALTH_BASE_DOMAIN
          report-lost:
            function: actions/report-lost/index.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotions:
              require-adobe-auth: false
              final: true
          authentication-costco-figo:
            function: actions/costco-figo-proxy/authentication.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              COSTCO_CLIENT_ID: $COSTCO_CLIENT_ID
              COSTCO_CLIENT_SECRET: $COSTCO_CLIENT_SECRET
              COSTCO_USERNAME: $COSTCO_USERNAME
              COSTCO_PASSWORD: $COSTCO_PASSWORD
              COSTCO_AUTH_URI: $COSTCO_AUTH_URI
          service-costco-figo:
            function: actions/costco-figo-proxy/service.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              COSTCO_REST_URI: $COSTCO_REST_URI
          authentication-salesforce-heroes:
            function: actions/salesforce-heroes-form/authentication.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              SFMC_HEROES_CLIENT_ID: $SFMC_HEROES_CLIENT_ID
              SFMC_HEROES_CLIENT_SECRET: $SFMC_HEROES_CLIENT_SECRET
              SFMC_HEROES_AUTH_URI: $SFMC_HEROES_AUTH_URI
              SFMC_HEROES_ACCOUNT_ID: $SFMC_HEROES_ACCOUNT_ID
              SFMC_HEROES_SCOPES: "offline list_and_subscribers_read list_and_subscribers_write data_extensions_read data_extensions_write"
          salesforce-heroes-event:
            function: actions/salesforce-heroes-form/salesforce.js
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              SFMC_HEROES_REST_EVENTS_URI: $SFMC_HEROES_REST_EVENTS_URI
              SFMC_HEROES_REST_EVENTS_UPSERT_URI: $SFMC_HEROES_REST_EVENTS_UPSERT_URI
              SFMC_HEROES_EVENT_DEFINITION: "APIEvent-6723a35b-b066-640c-1d7b-222f98caa9e1"
          recaptcha-24pet:
            function: actions/recaptcha-24pet/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotions:
              require-adobe-auth: false
              final: true
        sequences:
          proxy-pethealth-services:
            actions: authentication-pethealth, service-pethealth
            web: 'yes'
          proxy-salesforce-services:
            actions: authentication-salesforce, salesfore-event
            web: 'yes'
          proxy-report-lost:
            actions: report-lost, authentication-pethealth, service-pethealth
            web: 'yes'
          proxy-costco-figo-services:
            actions: authentication-costco-figo, service-costco-figo
            web: 'yes'
          proxy-salesforce-heroes-services:
            actions: authentication-salesforce-heroes, salesforce-heroes-event
            web: 'yes'
